version: '3'
services:
  redis: 
    image: redis:7.0.4
    restart: "no"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - ./data:/data
    command: redis-server /etc/redis/redis.conf --appendonly yes
    privileged: true