version: '3'
services:
  redis: 
    image: redis:7.0.4
    restart: "no"
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - ./data:/data
    command: redis-server /etc/redis/redis.conf --appendonly yes
    privileged: true
    networks:
      - server
  pastebin-server:
    image: moreality/pastebin-server:latest
    container_name: pastebin
    depends_on: 
      - "redis"
    ports: 
      - "9989:9989"
    networks:
      - server
    volumes:
      - ./config.yml:/config.yml

networks:
  server:
    driver:
      bridge